In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv(filepath_or_buffer='./data/air_data.csv',encoding='utf-8')
result=df.describe()

In [3]:
result

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>MEMBER_NO</th>
      <th>FFP_TIER</th>
      <th>AGE</th>
      <th>FLIGHT_COUNT</th>
      <th>BP_SUM</th>
      <th>EP_SUM_YR_1</th>
      <th>EP_SUM_YR_2</th>
      <th>SUM_YR_1</th>
      <th>SUM_YR_2</th>
      <th>SEG_KM_SUM</th>
      <th>...</th>
      <th>ADD_Point_SUM</th>
      <th>Eli_Add_Point_Sum</th>
      <th>L1Y_ELi_Add_Points</th>
      <th>Points_Sum</th>
      <th>L1Y_Points_Sum</th>
      <th>Ration_L1Y_Flight_Count</th>
      <th>Ration_P1Y_Flight_Count</th>
      <th>Ration_P1Y_BPS</th>
      <th>Ration_L1Y_BPS</th>
      <th>Point_NotFlight</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>count</th>
      <td>62988.000000</td>
      <td>62988.000000</td>
      <td>62568.000000</td>
      <td>62988.000000</td>
      <td>62988.000000</td>
      <td>62988.0</td>
      <td>62988.000000</td>
      <td>62437.000000</td>
      <td>62850.000000</td>
      <td>62988.000000</td>
      <td>...</td>
      <td>62988.000000</td>
      <td>62988.000000</td>
      <td>62988.000000</td>
      <td>62988.0000</td>
      <td>62988.000000</td>
      <td>62988.000000</td>
      <td>62988.000000</td>
      <td>62988.000000</td>
      <td>62988.000000</td>
      <td>62988.000000</td>
    </tr>
    <tr>
      <th>mean</th>
      <td>31494.500000</td>
      <td>4.102162</td>
      <td>42.476346</td>
      <td>11.839414</td>
      <td>10925.081254</td>
      <td>0.0</td>
      <td>265.689623</td>
      <td>5355.376064</td>
      <td>5604.026014</td>
      <td>17123.878691</td>
      <td>...</td>
      <td>1355.006223</td>
      <td>1620.695847</td>
      <td>1080.378882</td>
      <td>12545.7771</td>
      <td>6638.739585</td>
      <td>0.486419</td>
      <td>0.513581</td>
      <td>0.522293</td>
      <td>0.468422</td>
      <td>2.728155</td>
    </tr>
    <tr>
      <th>std</th>
      <td>18183.213715</td>
      <td>0.373856</td>
      <td>9.885915</td>
      <td>14.049471</td>
      <td>16339.486151</td>
      <td>0.0</td>
      <td>1645.702854</td>
      <td>8109.450147</td>
      <td>8703.364247</td>
      <td>20960.844623</td>
      <td>...</td>
      <td>7868.477000</td>
      <td>8294.398955</td>
      <td>5639.857254</td>
      <td>20507.8167</td>
      <td>12601.819863</td>
      <td>0.319105</td>
      <td>0.319105</td>
      <td>0.339632</td>
      <td>0.338956</td>
      <td>7.364164</td>
    </tr>
    <tr>
      <th>min</th>
      <td>1.000000</td>
      <td>4.000000</td>
      <td>6.000000</td>
      <td>2.000000</td>
      <td>0.000000</td>
      <td>0.0</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>368.000000</td>
      <td>...</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.0000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>25%</th>
      <td>15747.750000</td>
      <td>4.000000</td>
      <td>35.000000</td>
      <td>3.000000</td>
      <td>2518.000000</td>
      <td>0.0</td>
      <td>0.000000</td>
      <td>1003.000000</td>
      <td>780.000000</td>
      <td>4747.000000</td>
      <td>...</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>2775.0000</td>
      <td>700.000000</td>
      <td>0.250000</td>
      <td>0.288889</td>
      <td>0.258150</td>
      <td>0.167954</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>50%</th>
      <td>31494.500000</td>
      <td>4.000000</td>
      <td>41.000000</td>
      <td>7.000000</td>
      <td>5700.000000</td>
      <td>0.0</td>
      <td>0.000000</td>
      <td>2800.000000</td>
      <td>2773.000000</td>
      <td>9994.000000</td>
      <td>...</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>6328.5000</td>
      <td>2860.500000</td>
      <td>0.500000</td>
      <td>0.500000</td>
      <td>0.514252</td>
      <td>0.476747</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>75%</th>
      <td>47241.250000</td>
      <td>4.000000</td>
      <td>48.000000</td>
      <td>15.000000</td>
      <td>12831.000000</td>
      <td>0.0</td>
      <td>0.000000</td>
      <td>6574.000000</td>
      <td>6845.750000</td>
      <td>21271.250000</td>
      <td>...</td>
      <td>0.000000</td>
      <td>345.000000</td>
      <td>0.000000</td>
      <td>14302.5000</td>
      <td>7500.000000</td>
      <td>0.711111</td>
      <td>0.750000</td>
      <td>0.815091</td>
      <td>0.728375</td>
      <td>1.000000</td>
    </tr>
    <tr>
      <th>max</th>
      <td>62988.000000</td>
      <td>6.000000</td>
      <td>110.000000</td>
      <td>213.000000</td>
      <td>505308.000000</td>
      <td>0.0</td>
      <td>74460.000000</td>
      <td>239560.000000</td>
      <td>234188.000000</td>
      <td>580717.000000</td>
      <td>...</td>
      <td>984938.000000</td>
      <td>984938.000000</td>
      <td>728282.000000</td>
      <td>985572.0000</td>
      <td>728282.000000</td>
      <td>1.000000</td>
      <td>1.000000</td>
      <td>0.999989</td>
      <td>0.999993</td>
      <td>140.000000</td>
    </tr>
  </tbody>
</table>
<p>8 rows × 36 columns</p>
</div>

In [4]:
df

<div>
<style>
    .dataframe thead tr:only-child th {
        text-align: right;
    }

    .dataframe thead th {
        text-align: left;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>MEMBER_NO</th>
      <th>FFP_DATE</th>
      <th>FIRST_FLIGHT_DATE</th>
      <th>GENDER</th>
      <th>FFP_TIER</th>
      <th>WORK_CITY</th>
      <th>WORK_PROVINCE</th>
      <th>WORK_COUNTRY</th>
      <th>AGE</th>
      <th>LOAD_TIME</th>
      <th>...</th>
      <th>ADD_Point_SUM</th>
      <th>Eli_Add_Point_Sum</th>
      <th>L1Y_ELi_Add_Points</th>
      <th>Points_Sum</th>
      <th>L1Y_Points_Sum</th>
      <th>Ration_L1Y_Flight_Count</th>
      <th>Ration_P1Y_Flight_Count</th>
      <th>Ration_P1Y_BPS</th>
      <th>Ration_L1Y_BPS</th>
      <th>Point_NotFlight</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>54993</td>
      <td>2006/11/02</td>
      <td>2008/12/24</td>
      <td>男</td>
      <td>6</td>
      <td>.</td>
      <td>北京</td>
      <td>CN</td>
      <td>31.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>39992</td>
      <td>114452</td>
      <td>111100</td>
      <td>619760</td>
      <td>370211</td>
      <td>0.509524</td>
      <td>0.490476</td>
      <td>0.487221</td>
      <td>0.512777</td>
      <td>50</td>
    </tr>
    <tr>
      <th>1</th>
      <td>28065</td>
      <td>2007/02/19</td>
      <td>2007/08/03</td>
      <td>男</td>
      <td>6</td>
      <td>NaN</td>
      <td>北京</td>
      <td>CN</td>
      <td>42.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>12000</td>
      <td>53288</td>
      <td>53288</td>
      <td>415768</td>
      <td>238410</td>
      <td>0.514286</td>
      <td>0.485714</td>
      <td>0.489289</td>
      <td>0.510708</td>
      <td>33</td>
    </tr>
    <tr>
      <th>2</th>
      <td>55106</td>
      <td>2007/02/01</td>
      <td>2007/08/30</td>
      <td>男</td>
      <td>6</td>
      <td>.</td>
      <td>北京</td>
      <td>CN</td>
      <td>40.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>15491</td>
      <td>55202</td>
      <td>51711</td>
      <td>406361</td>
      <td>233798</td>
      <td>0.518519</td>
      <td>0.481481</td>
      <td>0.481467</td>
      <td>0.518530</td>
      <td>26</td>
    </tr>
    <tr>
      <th>3</th>
      <td>21189</td>
      <td>2008/08/22</td>
      <td>2008/08/23</td>
      <td>男</td>
      <td>5</td>
      <td>Los Angeles</td>
      <td>CA</td>
      <td>US</td>
      <td>64.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>0</td>
      <td>34890</td>
      <td>34890</td>
      <td>372204</td>
      <td>186100</td>
      <td>0.434783</td>
      <td>0.565217</td>
      <td>0.551722</td>
      <td>0.448275</td>
      <td>12</td>
    </tr>
    <tr>
      <th>4</th>
      <td>39546</td>
      <td>2009/04/10</td>
      <td>2009/04/15</td>
      <td>男</td>
      <td>6</td>
      <td>贵阳</td>
      <td>贵州</td>
      <td>CN</td>
      <td>48.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>22704</td>
      <td>64969</td>
      <td>64969</td>
      <td>338813</td>
      <td>210365</td>
      <td>0.532895</td>
      <td>0.467105</td>
      <td>0.469054</td>
      <td>0.530943</td>
      <td>39</td>
    </tr>
    <tr>
      <th>5</th>
      <td>56972</td>
      <td>2008/02/10</td>
      <td>2009/09/29</td>
      <td>男</td>
      <td>6</td>
      <td>广州</td>
      <td>广东</td>
      <td>CN</td>
      <td>64.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>2460</td>
      <td>29783</td>
      <td>29783</td>
      <td>343121</td>
      <td>152538</td>
      <td>0.456522</td>
      <td>0.543478</td>
      <td>0.608233</td>
      <td>0.391764</td>
      <td>15</td>
    </tr>
    <tr>
      <th>6</th>
      <td>44924</td>
      <td>2006/03/22</td>
      <td>2006/03/29</td>
      <td>男</td>
      <td>6</td>
      <td>乌鲁木齐市</td>
      <td>新疆</td>
      <td>CN</td>
      <td>46.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>12320</td>
      <td>50009</td>
      <td>50009</td>
      <td>298873</td>
      <td>175673</td>
      <td>0.504950</td>
      <td>0.495050</td>
      <td>0.495048</td>
      <td>0.504948</td>
      <td>29</td>
    </tr>
    <tr>
      <th>7</th>
      <td>22631</td>
      <td>2010/04/09</td>
      <td>2010/04/09</td>
      <td>女</td>
      <td>6</td>
      <td>温州市</td>
      <td>浙江</td>
      <td>CN</td>
      <td>50.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>9500</td>
      <td>49334</td>
      <td>49334</td>
      <td>351198</td>
      <td>193601</td>
      <td>0.589041</td>
      <td>0.410959</td>
      <td>0.522078</td>
      <td>0.477919</td>
      <td>14</td>
    </tr>
    <tr>
      <th>8</th>
      <td>32197</td>
      <td>2011/06/07</td>
      <td>2011/07/01</td>
      <td>男</td>
      <td>5</td>
      <td>DRANCY</td>
      <td>NaN</td>
      <td>FR</td>
      <td>50.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>500</td>
      <td>32200</td>
      <td>32200</td>
      <td>295158</td>
      <td>168028</td>
      <td>0.410714</td>
      <td>0.589286</td>
      <td>0.483459</td>
      <td>0.516537</td>
      <td>7</td>
    </tr>
    <tr>
      <th>9</th>
      <td>31645</td>
      <td>2010/07/05</td>
      <td>2010/07/05</td>
      <td>女</td>
      <td>6</td>
      <td>温州</td>
      <td>浙江</td>
      <td>CN</td>
      <td>43.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>0</td>
      <td>47052</td>
      <td>47052</td>
      <td>251907</td>
      <td>143958</td>
      <td>0.390625</td>
      <td>0.609375</td>
      <td>0.526951</td>
      <td>0.473044</td>
      <td>16</td>
    </tr>
    <tr>
      <th>10</th>
      <td>58877</td>
      <td>2010/11/18</td>
      <td>2010/11/20</td>
      <td>女</td>
      <td>6</td>
      <td>PARIS</td>
      <td>PARIS</td>
      <td>FR</td>
      <td>34.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>500</td>
      <td>39518</td>
      <td>39518</td>
      <td>337839</td>
      <td>197445</td>
      <td>0.534884</td>
      <td>0.465116</td>
      <td>0.470612</td>
      <td>0.529384</td>
      <td>3</td>
    </tr>
    <tr>
      <th>11</th>
      <td>37994</td>
      <td>2004/11/13</td>
      <td>2004/12/02</td>
      <td>男</td>
      <td>6</td>
      <td>北京</td>
      <td>.</td>
      <td>CN</td>
      <td>47.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>52469</td>
      <td>97008</td>
      <td>76998</td>
      <td>353101</td>
      <td>231452</td>
      <td>0.606897</td>
      <td>0.393103</td>
      <td>0.396882</td>
      <td>0.603114</td>
      <td>66</td>
    </tr>
    <tr>
      <th>12</th>
      <td>28012</td>
      <td>2006/11/23</td>
      <td>2007/11/18</td>
      <td>男</td>
      <td>5</td>
      <td>SAN MARINO</td>
      <td>CA</td>
      <td>US</td>
      <td>58.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>0</td>
      <td>35539</td>
      <td>35539</td>
      <td>245808</td>
      <td>156214</td>
      <td>0.517241</td>
      <td>0.482759</td>
      <td>0.426090</td>
      <td>0.573905</td>
      <td>4</td>
    </tr>
    <tr>
      <th>13</th>
      <td>54943</td>
      <td>2006/10/25</td>
      <td>2007/10/27</td>
      <td>男</td>
      <td>6</td>
      <td>深圳</td>
      <td>广东</td>
      <td>CN</td>
      <td>47.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>2664</td>
      <td>29090</td>
      <td>26426</td>
      <td>270704</td>
      <td>158779</td>
      <td>0.559322</td>
      <td>0.440678</td>
      <td>0.452211</td>
      <td>0.547785</td>
      <td>20</td>
    </tr>
    <tr>
      <th>14</th>
      <td>57881</td>
      <td>2010/02/01</td>
      <td>2010/02/01</td>
      <td>女</td>
      <td>6</td>
      <td>广州</td>
      <td>广东</td>
      <td>CN</td>
      <td>45.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>400</td>
      <td>38428</td>
      <td>38028</td>
      <td>328345</td>
      <td>186491</td>
      <td>0.500000</td>
      <td>0.500000</td>
      <td>0.487910</td>
      <td>0.512086</td>
      <td>12</td>
    </tr>
    <tr>
      <th>15</th>
      <td>1254</td>
      <td>2008/03/28</td>
      <td>2008/04/05</td>
      <td>男</td>
      <td>4</td>
      <td>BOWLAND HEIGHTS</td>
      <td>CALIFORNIA</td>
      <td>US</td>
      <td>63.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>500</td>
      <td>23838</td>
      <td>23838</td>
      <td>310002</td>
      <td>143671</td>
      <td>0.500000</td>
      <td>0.500000</td>
      <td>0.581242</td>
      <td>0.418755</td>
      <td>8</td>
    </tr>
    <tr>
      <th>16</th>
      <td>8253</td>
      <td>2010/07/15</td>
      <td>2010/08/20</td>
      <td>男</td>
      <td>6</td>
      <td>乌鲁木齐</td>
      <td>新疆</td>
      <td>CN</td>
      <td>48.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>13817</td>
      <td>37198</td>
      <td>37198</td>
      <td>257193</td>
      <td>151717</td>
      <td>0.544554</td>
      <td>0.455446</td>
      <td>0.479445</td>
      <td>0.520550</td>
      <td>22</td>
    </tr>
    <tr>
      <th>17</th>
      <td>58899</td>
      <td>2010/11/10</td>
      <td>2011/02/23</td>
      <td>女</td>
      <td>6</td>
      <td>PARIS</td>
      <td>NaN</td>
      <td>FR</td>
      <td>50.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>0</td>
      <td>31823</td>
      <td>31823</td>
      <td>281705</td>
      <td>137196</td>
      <td>0.625000</td>
      <td>0.375000</td>
      <td>0.578307</td>
      <td>0.421689</td>
      <td>13</td>
    </tr>
    <tr>
      <th>18</th>
      <td>26955</td>
      <td>2006/04/06</td>
      <td>2007/02/22</td>
      <td>男</td>
      <td>6</td>
      <td>乌鲁木齐市</td>
      <td>新疆</td>
      <td>CN</td>
      <td>54.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>12865</td>
      <td>34901</td>
      <td>34901</td>
      <td>249914</td>
      <td>139498</td>
      <td>0.500000</td>
      <td>0.500000</td>
      <td>0.513529</td>
      <td>0.486466</td>
      <td>23</td>
    </tr>
    <tr>
      <th>19</th>
      <td>41616</td>
      <td>2011/08/29</td>
      <td>2011/10/22</td>
      <td>男</td>
      <td>6</td>
      <td>东莞</td>
      <td>广东</td>
      <td>CN</td>
      <td>41.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>0</td>
      <td>24656</td>
      <td>24656</td>
      <td>215694</td>
      <td>116995</td>
      <td>0.473684</td>
      <td>0.526316</td>
      <td>0.516643</td>
      <td>0.483352</td>
      <td>3</td>
    </tr>
    <tr>
      <th>20</th>
      <td>21501</td>
      <td>2008/07/30</td>
      <td>2008/11/21</td>
      <td>男</td>
      <td>6</td>
      <td>.</td>
      <td>北京</td>
      <td>CN</td>
      <td>49.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>0</td>
      <td>30493</td>
      <td>30493</td>
      <td>251134</td>
      <td>176428</td>
      <td>0.584906</td>
      <td>0.415094</td>
      <td>0.338585</td>
      <td>0.661411</td>
      <td>9</td>
    </tr>
    <tr>
      <th>21</th>
      <td>41281</td>
      <td>2011/06/07</td>
      <td>2011/06/09</td>
      <td>男</td>
      <td>6</td>
      <td>VECHEL</td>
      <td>NORD BRABANT</td>
      <td>AN</td>
      <td>NaN</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>1000</td>
      <td>30947</td>
      <td>30947</td>
      <td>286520</td>
      <td>188808</td>
      <td>0.652174</td>
      <td>0.347826</td>
      <td>0.382324</td>
      <td>0.617672</td>
      <td>9</td>
    </tr>
    <tr>
      <th>22</th>
      <td>47229</td>
      <td>2005/04/10</td>
      <td>2005/04/10</td>
      <td>男</td>
      <td>6</td>
      <td>广州</td>
      <td>广东</td>
      <td>CN</td>
      <td>69.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>49003</td>
      <td>84225</td>
      <td>67205</td>
      <td>277394</td>
      <td>188661</td>
      <td>0.542553</td>
      <td>0.457447</td>
      <td>0.371243</td>
      <td>0.628752</td>
      <td>46</td>
    </tr>
    <tr>
      <th>23</th>
      <td>28474</td>
      <td>2010/04/13</td>
      <td>2010/04/13</td>
      <td>男</td>
      <td>6</td>
      <td>NaN</td>
      <td>CA</td>
      <td>US</td>
      <td>41.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>0</td>
      <td>24423</td>
      <td>24423</td>
      <td>280760</td>
      <td>127944</td>
      <td>0.350000</td>
      <td>0.650000</td>
      <td>0.596150</td>
      <td>0.403846</td>
      <td>9</td>
    </tr>
    <tr>
      <th>24</th>
      <td>58472</td>
      <td>2010/02/14</td>
      <td>2010/03/01</td>
      <td>女</td>
      <td>5</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>FR</td>
      <td>48.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>500</td>
      <td>31138</td>
      <td>31138</td>
      <td>235939</td>
      <td>160312</td>
      <td>0.613636</td>
      <td>0.386364</td>
      <td>0.369269</td>
      <td>0.630726</td>
      <td>12</td>
    </tr>
    <tr>
      <th>25</th>
      <td>13942</td>
      <td>2010/10/14</td>
      <td>2010/11/01</td>
      <td>男</td>
      <td>6</td>
      <td>PARIS</td>
      <td>FRANCE</td>
      <td>FR</td>
      <td>39.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>900</td>
      <td>33163</td>
      <td>32763</td>
      <td>274882</td>
      <td>152718</td>
      <td>0.677419</td>
      <td>0.322581</td>
      <td>0.503740</td>
      <td>0.496256</td>
      <td>10</td>
    </tr>
    <tr>
      <th>26</th>
      <td>45075</td>
      <td>2007/02/01</td>
      <td>2007/03/23</td>
      <td>男</td>
      <td>6</td>
      <td>湛江</td>
      <td>广东</td>
      <td>CN</td>
      <td>46.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>556788</td>
      <td>577589</td>
      <td>384620</td>
      <td>795398</td>
      <td>474610</td>
      <td>0.446009</td>
      <td>0.553991</td>
      <td>0.586837</td>
      <td>0.413158</td>
      <td>49</td>
    </tr>
    <tr>
      <th>27</th>
      <td>47114</td>
      <td>2005/01/15</td>
      <td>2005/03/17</td>
      <td>男</td>
      <td>6</td>
      <td>.</td>
      <td>北京</td>
      <td>CN</td>
      <td>47.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>5322</td>
      <td>25366</td>
      <td>22504</td>
      <td>235176</td>
      <td>119623</td>
      <td>0.459459</td>
      <td>0.540541</td>
      <td>0.537107</td>
      <td>0.462888</td>
      <td>14</td>
    </tr>
    <tr>
      <th>28</th>
      <td>54619</td>
      <td>2006/01/07</td>
      <td>2006/01/08</td>
      <td>男</td>
      <td>6</td>
      <td>广州</td>
      <td>广东</td>
      <td>CN</td>
      <td>62.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>3552</td>
      <td>28425</td>
      <td>24873</td>
      <td>237787</td>
      <td>143047</td>
      <td>0.514851</td>
      <td>0.485149</td>
      <td>0.435550</td>
      <td>0.564445</td>
      <td>11</td>
    </tr>
    <tr>
      <th>29</th>
      <td>12349</td>
      <td>2008/06/16</td>
      <td>2008/06/27</td>
      <td>男</td>
      <td>6</td>
      <td>深圳</td>
      <td>广东</td>
      <td>CN</td>
      <td>46.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>1776</td>
      <td>24215</td>
      <td>22439</td>
      <td>224081</td>
      <td>137148</td>
      <td>0.517241</td>
      <td>0.482759</td>
      <td>0.426068</td>
      <td>0.573927</td>
      <td>15</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>62958</th>
      <td>52412</td>
      <td>2013/02/22</td>
      <td>2013/02/22</td>
      <td>男</td>
      <td>4</td>
      <td>台北</td>
      <td>NaN</td>
      <td>TW</td>
      <td>24.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>700</td>
      <td>200</td>
      <td>0.500000</td>
      <td>0.500000</td>
      <td>0.713267</td>
      <td>0.285307</td>
      <td>0</td>
    </tr>
    <tr>
      <th>62959</th>
      <td>47026</td>
      <td>2013/03/03</td>
      <td>2013/07/28</td>
      <td>男</td>
      <td>4</td>
      <td>化州</td>
      <td>广东</td>
      <td>CN</td>
      <td>25.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0</td>
    </tr>
    <tr>
      <th>62960</th>
      <td>11699</td>
      <td>2008/02/13</td>
      <td>2013/07/15</td>
      <td>女</td>
      <td>4</td>
      <td>南宁</td>
      <td>广西</td>
      <td>CN</td>
      <td>73.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>1.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0</td>
    </tr>
    <tr>
      <th>62961</th>
      <td>3305</td>
      <td>2009/12/12</td>
      <td>2009/12/13</td>
      <td>男</td>
      <td>4</td>
      <td>陵水</td>
      <td>海南</td>
      <td>CN</td>
      <td>46.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>400</td>
      <td>0</td>
      <td>0.000000</td>
      <td>1.000000</td>
      <td>0.997506</td>
      <td>0.000000</td>
      <td>0</td>
    </tr>
    <tr>
      <th>62962</th>
      <td>5515</td>
      <td>2011/07/17</td>
      <td>2011/07/17</td>
      <td>男</td>
      <td>4</td>
      <td>广州</td>
      <td>广东</td>
      <td>CN</td>
      <td>31.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>400</td>
      <td>0</td>
      <td>0.000000</td>
      <td>1.000000</td>
      <td>0.997506</td>
      <td>0.000000</td>
      <td>0</td>
    </tr>
    <tr>
      <th>62963</th>
      <td>10999</td>
      <td>2004/12/16</td>
      <td>2004/12/18</td>
      <td>女</td>
      <td>4</td>
      <td>南海市</td>
      <td>广东省</td>
      <td>CN</td>
      <td>60.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>400</td>
      <td>400</td>
      <td>1.000000</td>
      <td>0.000000</td>
      <td>0.000000</td>
      <td>0.997506</td>
      <td>0</td>
    </tr>
    <tr>
      <th>62964</th>
      <td>34341</td>
      <td>2013/01/31</td>
      <td>2013/01/31</td>
      <td>男</td>
      <td>4</td>
      <td>SURABAYA</td>
      <td>JAWATIMUR</td>
      <td>ID</td>
      <td>40.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>400</td>
      <td>0</td>
      <td>0.000000</td>
      <td>1.000000</td>
      <td>0.997506</td>
      <td>0.000000</td>
      <td>0</td>
    </tr>
    <tr>
      <th>62965</th>
      <td>57428</td>
      <td>2008/12/05</td>
      <td>2008/12/05</td>
      <td>女</td>
      <td>4</td>
      <td>广州</td>
      <td>广东</td>
      <td>CN</td>
      <td>34.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>400</td>
      <td>0</td>
      <td>0.000000</td>
      <td>1.000000</td>
      <td>0.997506</td>
      <td>0.000000</td>
      <td>0</td>
    </tr>
    <tr>
      <th>62966</th>
      <td>60676</td>
      <td>2012/07/12</td>
      <td>2013/02/08</td>
      <td>男</td>
      <td>4</td>
      <td>RIYADH</td>
      <td>NaN</td>
      <td>AA</td>
      <td>37.0</td>
      <td>2014/03/31</td>
      <td>...</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>400</td>